@baseUrl = http://localhost:5075

### List of Games
GET {{baseUrl}}/games

### Get single game with id=2
GET {{baseUrl}}/games/2

### Create new game
POST {{baseUrl}}/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Kids and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

### Create game with bad data
POST {{baseUrl}}/games
Content-Type: application/json

{
  "genre": "Kids and Family",
  "price": 0,
  "releaseDate": "2011-11-18"
}

### Edit a game with id=2
PUT {{baseUrl}}/games/2
Content-Type: application/json

{
  "id": 2,
  "name": "Street Fighter II Turbo",
  "genre": "Fighting",
  "price": 9.99,
  "releaseDate": "1992-07-15"
}

### Edit a game with id=2 with bad data
PUT {{baseUrl}}/games/2
Content-Type: application/json

{
  "id": 2,
  "name": "Street Fighter II Turbo Street Fighter II TurboStreet Fighter II TurboStreet Fighter II TurboStreet Fighter II Turbo",
  "price": 20000,
  "releaseDate": "1992-07-15"
}

### Delete a game with id=2
DELETE {{baseUrl}}/games/2